---
title: "Data Wrangling"
author: "Ararat Çetinkaya"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

``` {r}

# Tidyverse
library(tidyverse)
library(vroom)

# Data Table
library(data.table)

# Counter
library(tictoc)

# DATA IMPORT ----

#patent_tbl

col_types_patent <- list(
  id = col_character(),
  date = col_date("%Y-%m-%d"),
  num_claims = col_double()
)

patent_tbl <- vroom(
  file       = "C:/Users/arara/OneDrive/Belgeler/GitHub/ss24-bdsb-araratcetinkaya/03_data_wrangling_files/Patent_data_reduced/patent.tsv", 
  delim      = "\t", 
  col_types  = col_types_patent,
  na         = c("", "NA", "NULL")
)


#patent_assignee_tbl

col_types_patent_assignee <- list(
  patent_id = col_character(),
  assignee_id = col_character()
)

patent_assignee_tbl <- vroom(
  file       = "C:/Users/arara/OneDrive/Belgeler/GitHub/ss24-bdsb-araratcetinkaya/03_data_wrangling_files/Patent_data_reduced/patent_assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types_patent_assignee,
  na         = c("", "NA", "NULL")
)


#assignee_tbl

col_types_assignee_tbl <- list(
  id = col_character(),
  type = col_integer(),
  organization = col_character()
)

assignee_tbl <- vroom(
  file       = "C:/Users/arara/OneDrive/Belgeler/GitHub/ss24-bdsb-araratcetinkaya/03_data_wrangling_files/Patent_data_reduced/assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types_assignee_tbl,
  na         = c("", "NA", "NULL")
)

#uspc_tbl

col_types_uspc_tbl <- list(
  patent_id = col_character(),
  mainclass_id = col_character(),
  sequence = col_integer()
)

uspc_tbl <- vroom(
  file       = "C:/Users/arara/OneDrive/Belgeler/GitHub/ss24-bdsb-araratcetinkaya/03_data_wrangling_files/Patent_data_reduced/uspc.tsv", 
  delim      = "\t", 
  col_types  = col_types_uspc_tbl,
  na         = c("", "NA", "NULL")
)



#setting data.table

setDT(patent_tbl)
setDT(patent_assignee_tbl)
setDT(assignee_tbl)
setDT(uspc_tbl)

# DATA WRANGLING ----

# combining data tables

#Table for question 1 - patent dominance

patent_dominance_q1 <- assignee_tbl %>% left_join( y=patent_assignee_tbl, by = c("id" = "assignee_id"))

#Table for question 2 - Recent patent activity

recent_patent_q2 <- patent_dominance_q1 %>% left_join( y=patent_tbl, by = c("patent_id" = "id"))

#Table for question 3 - Innovation in tech

innovation_tech_q3 <- patent_dominance_q1 %>% left_join( y=uspc_tbl, by = "patent_id")


# DATA ANALYSIS ----

#Question 1 patent dominance

## Patent types for USA based organizations and individuals are taken from excel

patent_dominance_USA_tbl <- patent_dominance_q1 %>%
  select(organization,type) %>%
  filter(type == c('2','4','6','8','9'))

organizationNumberUSA <- table(patent_dominance_USA_tbl$organization) %>%
  as.data.frame() %>%
  rename('Organization' = 'Var1') %>%
  arrange(desc(Freq)) %>%
  slice(1:10)%>%
  as_tibble()

organizationNumberUSA
###IBM has the most patents in USA


#Question 2 Recent patent activity

patent_august2014_tbl <- recent_patent_q2 %>%
  select(organization, date, num_claims)  %>%
  mutate(month = month(date)) %>%
  filter(month==8) %>%
  select(-num_claims, -date) %>%
  count(organization) %>% 
  rename("PatentNumber" = "n" ) %>% 
  arrange(desc(PatentNumber)) %>%
  slice(1:10)%>%
  as_tibble()

patent_august2014_tbl
#IBM has the most patents in August 2014

#Question 3 Innovation in Tech


uspto_mainclass_tbl <- innovation_tech_q3 %>%
  select(organization,mainclass_id)

organizationNumberWW <- table(uspto_mainclass_tbl$organization) %>%
  as.data.frame() %>%
  rename('organization' = 'Var1') %>%
  arrange(desc(Freq)) %>%
  slice(1:10)%>%
  as_tibble()

organizationNumberWW #Top10 worldwide companies with the most patent

organizationNumberWW <- organizationNumberWW %>% left_join( y=uspto_mainclass_tbl, by = "organization")


mainclassNumber <- table(organizationNumberWW$mainclass_id) %>%
  as.data.frame() %>%
  rename('USPTO Main Class ID' = 'Var1') %>%
  arrange(desc(Freq)) %>%
  slice(1:5)%>%
  as_tibble()

mainclassNumber











```
